[tool.poetry]
name = "pythonproject"
version = "0.1.0"
description = ""
authors = ["58255 <582556672@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
